require 'sqlite3'
require 'digest'
require './lib/reportmessage'

class ReportMessageDatabase

  TABLE_DML = 'create table reportmessages (
    id text not null primary key,
    recipient text,
    report_timestamp integer,
    message_timestamp integer,
    has_two_timestamps integer,
    timestamp_difference integer,
    subreddit text,
    violation text,
    violation_type text,
    first_report text,
    reported_account text,
    user_action text,
    content_action text,
    autogenerated_username text,
    reported_content_type text
  );'
  TABLE_DML_HASH = Digest::SHA256.hexdigest(TABLE_DML)


  def initialize()
    @db = SQLite3::Database.new 'reportmessages.sqlite3'

    create_tables()
  end


  def create_tables()
    puts "Creating tables as needed"

    # Create table for schema version first
    rows = @db.execute <<-SQLCREATEVERSIONTABLE
      create table if not exists version (
        version text primary key
      );
    SQLCREATEVERSIONTABLE

    # Fetch current version from database
    statement = @db.prepare 'select version from version'
    rows = statement.execute
    row = rows.next
    if row == nil
      version_in_database = 0
    else
      version_in_database = row[0]
    end
    statement.close

    puts " Version in database: #{version_in_database}"
    puts " Current version:     #{TABLE_DML_HASH}"
    if version_in_database == nil or version_in_database != TABLE_DML_HASH
      puts " Updating table definition"
      statement = @db.prepare 'delete from version'
      statement.execute
      statement.close

      statement = @db.prepare 'insert into version (version) values (?)'
      statement.bind_params TABLE_DML_HASH
      statement.execute
      statement.close

      rows = @db.execute <<-SQLDROP
        drop table if exists reportmessages;
      SQLDROP
      rows = @db.execute TABLE_DML
    else
      puts " No need to update"
    end
  end


  def save(report_message)
    # make sure the entry exists
    statement = @db.prepare 'insert or ignore
                               into reportmessages (id)
                             values (?)'
    statement.bind_params report_message.id
    rows = statement.execute

    # now fill in the values
    statement = @db.prepare 'update reportmessages
                             set reported_account = ?,
                                 recipient = ?,
                                 subreddit = ?,
                                 violation = ?,
                                 violation_type = ?,
                                 user_action = ?,
                                 content_action = ?,
                                 message_timestamp = ?,
                                 report_timestamp = ?,
                                 has_two_timestamps = ?,
                                 timestamp_difference = ?,
                                 first_report = ?,
                                 autogenerated_username = ?,
                                 reported_content_type = ?
                             where id = ?'
    statement.bind_params report_message.reported_account,
                          report_message.recipient,
                          report_message.subreddit,
                          report_message.violation?,
                          report_message.violation_type,
                          report_message.user_action,
                          report_message.content_action,
                          report_message.message_timestamp,
                          report_message.report_timestamp,
                          (report_message.report_timestamp == nil) ? 0 : 1,
                          report_message.message_timestamp.to_i - report_message.report_timestamp.to_i,
                          report_message.first_report?,
                          report_message.autogenerated_username?,
                          report_message.reported_content_type,
                          report_message.id
    rows = statement.execute
    statement.close
  end


  def list_all
    statement = @db.prepare 'select * from reportmessages order by reported_account asc'
    rows = statement.execute

    while (row = rows.next) do
      puts row.join "\s"
    end
    statement.close
  end


  def print_subreddit_stats(rows_in_subreddit_breakdown = -1)
    statement = @db.prepare 'select count(*) from (
                               select distinct subreddit
                                 from reportmessages
                             )' 

    row = statement.execute
    puts "Subreddits: #{row.next[0]}"
    statement.close

    if rows_in_subreddit_breakdown != 0
      statement = @db.prepare 'select subreddit, count(*)
                                from reportmessages
                                group by subreddit
                                order by 2 desc
                                limit ?'
      statement.bind_params rows_in_subreddit_breakdown
      rows = statement.execute
      if (rows_in_subreddit_breakdown > 0)
        puts "Subreddit breakdown: (Top #{rows_in_subreddit_breakdown})"
      else
        puts "Subreddit breakdown:"
      end
      while (row = rows.next)
        puts " '#{row[0]}': #{row[1]}"
      end
      statement.close
    end
  end


  def print_ban_stats
    statement = @db.prepare 'select count(*) from (
                               select distinct reported_account
                                 from reportmessages
                                where user_action like \'%permanent%\'
                             )' 

    row = statement.execute
    puts "Permanent bans: #{row.next[0]}"
    statement.close

    statement = @db.prepare 'select count(*) from (
                               select distinct reported_account
                                 from reportmessages
                                where user_action like \'%tempo%\'
                             )' 

    row = statement.execute
    puts "Temporary bans: #{row.next[0]}"
    statement.close
  end


  def print_violation_type_stats
    statement = @db.prepare 'select violation_type, count(*)
                               from reportmessages
                              group by violation_type
                              order by 2 desc'
    rows = statement.execute
    puts "Violation breakdown:"
    while (row = rows.next)
      puts " '#{row[0]}': #{row[1]}"
    end
    statement.close
  end


  def print_removal_stats
    statement = @db.prepare 'select count(*)
                               from reportmessages
                              where content_action like \'%removed%\''
    rows = statement.execute
    puts "Items removed: #{rows.next[0]}"
    statement.close
  end


  def print_reported_content_type_stats
    statement = @db.prepare 'select count(*)
                               from reportmessages
                              where reported_content_type = \'post\''
    rows = statement.execute
    puts "Posts: #{rows.next[0]}"
    statement.close

    statement = @db.prepare 'select count(*)
                               from reportmessages
                              where reported_content_type = \'comment\''
    rows = statement.execute
    puts "Comments: #{rows.next[0]}"
    statement.close
  end

  def print_time_stats
    statement = @db.prepare 'select min(message_timestamp), id
                               from reportmessages'
    rows = statement.execute
    row = rows.next
    puts "Oldest message: #{ReportMessage.timestamp_as_date(row[0])} (#{row[1]})"
    statement.close

    statement = @db.prepare 'select max(message_timestamp), id
                               from reportmessages'
    rows = statement.execute
    row = rows.next
    puts "Newest message: #{ReportMessage.timestamp_as_date(row[0])} (#{row[1]})"
    statement.close

    statement = @db.prepare 'select max(timestamp_difference), id
                               from reportmessages
                              where has_two_timestamps = 1'
    rows = statement.execute
    row = rows.next
    puts "Longest reaction time:  #{ReportMessage.format_processing_time(row[0])} (#{row[1]})"
    statement.close

    statement = @db.prepare 'select min(timestamp_difference), id
                               from reportmessages
                              where has_two_timestamps = 1'
    rows = statement.execute
    row = rows.next
    puts "Shortest reaction time: #{ReportMessage.format_processing_time(row[0])} (#{row[1]})"
    statement.close

    statement = @db.prepare 'select avg(timestamp_difference)
                               from reportmessages
                              where has_two_timestamps = 1'
    rows = statement.execute
    row = rows.next
    puts "Average reaction time:  #{ReportMessage.format_processing_time(row[0])}"
    statement.close
  end


  def print_violation_stats
    statement = @db.prepare 'select count(*)
                               from reportmessages
                              where violation = \'yes\''
    rows = statement.execute
    violations = rows.next[0]
    puts "Confirmed violations: #{violations}"
    statement.close

    statement = @db.prepare 'select count(*)
                               from reportmessages
                              where violation = \'no\''
    rows = statement.execute
    no_violations = rows.next[0]
    puts "No violation: #{no_violations}"
    statement.close

    puts "Successful: #{violations / ((violations + no_violations) / 100)}%"
  end

  
  def print_username_stats
    statement = @db.prepare 'select count(*)
                               from reportmessages
                              where autogenerated_username = \'yes\''
    rows = statement.execute
    autogenerated_usernames = rows.next[0]
    puts "Autogenerated names: #{autogenerated_usernames}"
    statement.close

    statement = @db.prepare 'select distinct reported_account
                               from reportmessages
                              where autogenerated_username = \'no\'
                              order by reported_account asc'
    rows = statement.execute
    print "Chosen usernames: "
    while (row = rows.next)
      print "'#{row[0]}', "
    end
    puts
    statement.close
  end


  def print_subreddit_css
    
  end

  def print_subreddit_details
    subreddits = Array.new

    statement = @db.prepare 'select distinct subreddit
                               from reportmessages'
    rows = statement.execute
    while (row = rows.next)
      subreddits << row[0]
    end
    statement.close

    subreddits.each { |sub|
      statement = @db.prepare 'select distinct reported_account
                                 from reportmessages
                                where subreddit = ?
                                  and violation = \'yes\''
      statement.bind_params sub
      rows = statement.execute
      puts "Sub: #{sub}"
      while (row = rows.next)
        print "#{row[0]} "
      end
      puts
      statement.close
    }

  end

  private :create_tables
end
