# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.2].define(version: 2024_09_25_125524) do
  create_table "report_messages", primary_key: "message_id", id: :string, force: :cascade do |t|
    t.string "recipient"
    t.datetime "report_timestamp"
    t.datetime "message_timestamp"
    t.boolean "subreddit_is_account_profile"
    t.boolean "is_violation"
    t.string "violation_type"
    t.boolean "first_report"
    t.string "reported_account"
    t.string "user_action"
    t.string "content_action"
    t.boolean "autogenerated_username"
    t.string "content_type"
    t.integer "subreddit_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "sender"
    t.string "permalink"
    t.text "body"
    t.index ["subreddit_id"], name: "index_report_messages_on_subreddit_id"
  end

  create_table "subreddits", primary_key: "name", id: :string, force: :cascade do |t|
    t.string "status"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end
