class CreateReportMessages < ActiveRecord::Migration[7.2]
  def change
    create_table :report_messages, id: :string, primary_key: :message_id do |t|
      t.string :recipient
      t.datetime :report_timestamp
      t.datetime :message_timestamp
      t.boolean :subreddit_is_account_profile
      t.boolean :is_violation
      t.string :violation_type
      t.boolean :first_report
      t.string :reported_account
      t.string :user_action
      t.string :content_action
      t.boolean :autogenerated_username
      t.string :content_type

      t.belongs_to :subreddit

      t.timestamps
    end
  end
end
